openapi: "3.0.2"
info:
  title: Audiobooks API
  version: "1.0"
servers:
  - url: https://127.0.0.1:3000/api

paths:
  /books/{id}/info.json:
    get:
      operationId: GetBook
      parameters:
        - name: id
          in: path
          description: Book ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Book data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
  /books.json:
    get:
      operationId: GetBooks
      responses:
        "200":
          description: Books list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Books"
  /authors.json:
    get:
      operationId: GetAuthors
      responses:
        "200":
          description: Authors list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Person"
  /readers.json:
    get:
      operationId: GetReaders
      responses:
        "200":
          description: Readers list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Person"
  /series.json:
    get:
      operationId: GetSeries
      responses:
        "200":
          description: Series list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Series"
components:
  schemas:
    BookInfo:
      type: object
      properties:
        name:
          type: string
        author_id:
          type: string
        reader_id:
          type: string
        series_id:
          type: string
        series_number:
          type: string
        cover:
          type: object
          $ref: "#/components/schemas/Cover"
      required: [name, author_id, reader_id]
    Book:
      type: object
      properties:
        info:
          type: object
          $ref: "#/components/schemas/BookInfo"
        chapters:
          type: array
          items:
            $ref: "#/components/schemas/Chapter"
      required: [info, chapters]
    Books:
      type: array
      items:
        type: object
        properties:
          id:
            type: string
          info:
            type: object
            $ref: "#/components/schemas/BookInfo"
        required: [id, info]
    Chapter:
      type: object
      properties:
        title:
          type: string
        filename:
          type: string
      required: [title, filename]
    Cover:
      type: object
      properties:
        type:
          type: string
        filename:
          type: string
      required: [type, filename]
    Person:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required: [id, name]
    Series:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        author_id:
          type: string
        books:
          type: array
          items:
            type: string
      required: [id, name, author_id, books]
