version: "3"
services:
  audiobooks-mongo:
    container_name: "audiobooks-mongo"
    image: "mongo"
    networks:
      - "audiobooks-mongo"
    volumes:
      - "${MONGO_STORAGE:-../db:/data/db}"
    restart: "always"
  audiobooks-backend:
    container_name: "audiobooks-backend"
    image: "node:18"
    depends_on:
      - "audiobooks-mongo"
    networks:
      - "audiobooks-mongo"
    ports: 
      - "4001:4000"
    volumes:
      - "../:/mnt/"
    working_dir: "/mnt/backend"
    restart: "always"
    environment:
      TZ: "Europe/Moscow"
    command: >
      sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && 
      echo $TZ > /etc/timezone &&
      exec npm run start:prod"
networks:
  audiobooks-mongo: